"""
Django settings for sanyu project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9)u%q@$$7_nf1_ak6f_7krh1c3z)0z7lpwenajuk2c_-$s_b1p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['sanyuhospital.org', 'www.sanyuhospital.org']



USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webapp',
    'django.contrib.sites',
    'django_pesapal',
    'widget_tweaks',
    'diaspora',
    'ckeditor',
]
X_FRAME_OPTIONS = 'ALLOWALL'

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sanyu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webapp.context_processors.partners_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanyu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sanyu',
        'USER': 'sanyu',
        'PASSWORD': 'sanyu',
        'HOST': 'localhost',
        'PORT': '5432',
        'CONN_MAX_AGE': 600,
    }
}


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
            ['Source', '-', 'Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'Link', 'Unlink', '-', 'Image', 'CodeSnippet', 'Table', '-', 'Font', 'FontSize', 'TextColor', 'BGColor', '-', 'Styles', 'Format', 'AlignLeft', 'AlignCenter', 'AlignRight', 'Justify', '-', 'Undo', 'Redo', '-', 'Maximize', '-', 'ShowBlocks'],
        ],
        'toolbarCanCollapse': True,
        'width': 'auto',
        'height': 300,
        'extraPlugins': ','.join([
            'div', 'autolink', 'autoembed', 'embedsemantic', 'autogrow',
            'widget', 'lineutils', 'clipboard', 'dialog', 'dialogui', 'elementspath'
        ]),
        'contentsCss': [
            '/static/ckeditor/contents.css',  # Important: default CKEditor CSS
            '/static/css/custom_ckeditor.css',  # Optional: your own styles
        ],
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # or os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

PESAPAL_TRANSACTION_DEFAULT_REDIRECT_URL = 'webapp:thank-you'

import os

# Default fallback path
SERVICE_KEY_PATH = 'serviceAccountKey.json'

# Try to override from Render's secret file if available
secret_file_path = '/etc/secrets/secret_key.txt'
if os.path.exists(secret_file_path):
    with open(secret_file_path) as f:
        SERVICE_KEY_PATH = f.read().strip()


SERVICE_ACCOUNT_URL = "https://firebasestorage.googleapis.com/v0/b/twinbrook-12f84.appspot.com/o/twinbrook-12f84-firebase-adminsdk-la9vk-02f288b2ba.json?alt=media&token=2abc1b23-5322-428f-ac9b-6fa9ac09b0b2"



